[package]
name = "opensim_runtime"
version = "0.1.0"
authors = ["Christopher Granade <cgranade@cgranade.com>"]
edition = "2018"

[features]
default = []

# When enabled, web-sys-log allows for logging runtime error messages and
# warnings via console.log.
web-sys-log = ["web-sys"]

[profile.release]
opt-level = 'z'     # Optimize for size.
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = 'unwind'
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = { version = "0.13.1", features = ["serde"] }
num-complex = { version = "0.2", features = ["serde"] }
num-traits = "0.2"
derive_more = "0.99.10"
itertools = "0.9.0"
rand = "0.7.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# See https://github.com/rust-random/rand/issues/990
# and https://docs.rs/getrandom/0.1.15/getrandom/index.html#support-for-webassembly-and-asmjs
# for why this is needed.
# NB: We depend on 0.1.15, since that's what gets brought in transitively
#    by rand and rand_core.
getrandom = { version = "0.1.15", features = ["wasm-bindgen"] }

# We only need web-sys when compiling with the web-sys-log feature.
web-sys = { version = "0.3.4",  features = ['console'], optional = true }

[lib]
name = "opensim_runtime"
path = "src/lib.rs"
# Build a Rust library from this crate. That can't be used directly except
# by other Rust crates, but allows us to retarget the runtime here as different
# kinds of libraries with thin wrappers later.
crate-type = ["rlib"]
